blogs:
- cf_project: rotcha-blog
  deploy_type: pages
  domain: rotcha.kr
  funnel_stage: landing
  id: rotcha-blog
  owner: mac
  managed_by: mde2
  name: 로차 블로그
  platform: hugo
  site_path: /Users/twinssn/Projects/rotcha-blog
  status: paused
- cf_project: informationhot-hugo
  deploy_type: pages
  domain: informationhot.kr
  funnel_stage: landing
  id: informationhot-hugo
  owner: mac
  managed_by: mde2
  name: 인포메이션핫
  pipeline: curation
  platform: hugo
  site_path: /Users/twinssn/Projects/informationhot-hugo
  status: active
- cf_project: techpawz-hugo
  deploy_type: pages
  domain: techpawz.com
  funnel_stage: landing
  id: techpawz-hugo
  owner: mac
  managed_by: mde2
  name: 테크포즈
  platform: hugo
  site_path: /Users/twinssn/Projects/techpawz-hugo
  status: paused
- cf_project: biz-techpawz
  deploy_type: pages
  domain: biz.techpawz.com
  funnel_stage: landing
  id: biz-techpawz-hugo
  owner: mac
  managed_by: mde2
  name: 테크포즈 비즈
  platform: hugo
  site_path: /Users/twinssn/Projects/biz.techpawz-hugo
  status: paused
- cf_project: issue-techpawz-hugo
  deploy_type: pages
  domain: issue.techpawz.com
  funnel_stage: landing
  id: issue-techpawz-hugo
  owner: mac
  managed_by: mde2
  name: 테크포즈 이슈
  platform: hugo
  site_path: /Users/twinssn/Projects/issue-techpawz-hugo
  status: paused
